---
title: "MBRP Genomics Notebook"
author: "Gisela H. Kopp"
date: "`r Sys.Date()`"
bibliography: book.bib
description: A diary-style notebook for this project
documentclass: book
editor_options:
  chunk_output_type: console
github-repo: https://github.com/GiselaHKopp/MBRP_genomics
link-citations: yes
subtitle: Project Notebook
biblio-style: apalike
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "#>",
                      collapse = TRUE)
knitr::opts_knit$set(root.dir = '../')
```


# Intro

Hello, 

this is a minimal {[bookdown](https://bookdown.org/)} diary-style notebook to document this project.

The documentation of this project is broken down into several chunks:

- [1 Intro](./index.html): General intro to the project (you are looking at this right now...)
- [2 Project development](./project-development.html): Here I keep a diary of the development of the project.
- [3 Notes](./project-notes.html): Notes on ideas, what should be or has been read, etc.
- [4 Data](./data.html): The data needed and compiled for the project.
- [5 Population Genomic Analysis](./analysis.html): The population genomic analysis. 
- [6 Pathogen Analysis](./analysis.html): The metagenomic pathogen analysis. 
- [7 References](./references.html): This is where session infor and all cited sources of your project will be listed.

## Dependencies

To be able to use this in your own projects you will need to `R` as well as the {bookdown} package installed:

```r
install.packages("bookdown")
```


Feel free to adapt this template to your needs.


---
